<?php
namespace HummingJay;
require 'HummingJay.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-19 at 21:48:05.
 */
class HummingJayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HummingJay
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HummingJay();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HummingJay\HummingJay::parseRouteString
     * @todo   Implement testParseRouteString().
     */
    public function testParseRouteString()                                            
    {
        $this->assertArrayHasKey(
            "/books",
            $this->object->parseRouteString("/books - Demo\\BooksCollection") , 
            "Test a single line route string"
        );

        $this->assertArrayHasKey(
            "/cars",
            $this->object->parseRouteString("/books - D \n/cars - C") , 
            "Test two line route string with UNIX line ending"
        );

        $this->assertArrayHasKey(
            "/cars",
            $this->object->parseRouteString("/books - D \r\n/cars - C"),
            "Test two line route string with Windows line ending"
        );


    }

    
    /**
     * @covers HummingJay\HummingJay::route
     * @todo   Implement testRoute().
     */
    public function testRoute()
    {
        
    }
}
