<?php
namespace HummingJay;

class TestResource extends Resource{
    // For testCallMethod

    public function get($server){
        $server->title = "Sitting Still Like a Frog";
        return $server;
    }
} 

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-19 at 22:02:00.
 */
class ResourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Resource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HummingJay\Resource::callMethod
     * @todo   Implement testCallMethod().
     */
    public function testCallMethod()
    {
        $server = new Server("");
        $server->method = "GET";
        $tr = new TestResource($server);
        $server = $tr->callMethod($server);

        $this->assertEquals(
            "Sitting Still Like a Frog",
            $server->title,
            "Returned title verifies that the get handler of our test resource was called."
        );

    }

    /**
     * @covers HummingJay\Resource::callMethod
     * @todo   Implement testHalt().
     */
    public function testHalt()
    {
        $server = new Server("");
        $server->method = "GET";
        $server->title = "As I Lay Dying";
        $tr = new TestResource($server);
        $tr->halt();
        $server = $tr->callMethod($server);

        $this->assertEquals(
            "As I Lay Dying",
            $server->title,
            "Returned title verifies that the get handler of our test resource was NOT called."
        );

    }
}


// Test callMethod