<?php
namespace HummingJay;

class TestResource extends Resource{
    // For testCallMethod

    public function get($req, $res){
        $res->title = "Sitting Still Like a Frog";
        return $res;
    }
} 

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-19 at 22:02:00.
 */
class ResourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Resource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Resource(NULL);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HummingJay\Resource::callMethod
     * @todo   Implement testCallMethod().
     */
    public function testCallMethod()
    {
        $req = new Request("");
        $req->method = "GET";
        $tr = new TestResource($req);
        $res = $tr->callMethod($req);

        $this->assertEquals(
            "Sitting Still Like a Frog",
            $res->title,
            "Returned title that verifies that the get handler of our test resource was called."
        );
    }
}


// Test callMethod