<?php
namespace HummingJay;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-19 at 22:02:53.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HummingJay\Response::send400
     * @todo   Implement testSend400().
     */
    public function testSend400()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::send404
     * @todo   Implement testSend404().
     */
    public function testSend404()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::send405
     * @todo   Implement testSend405(). 
     */
    public function testSend405()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::send500
     * @todo   Implement testSend500().
     */
    public function testSend500()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::send
     * @todo   Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::hyperTitle
     * @todo   Implement testHyperTitle().
     */
    public function testHyperTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::hyperDescription
     * @todo   Implement testHyperDescription().
     */
    public function testHyperDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::hyperLink
     * @todo   Implement testHyperLink().
     */
    public function testHyperLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::addData
     * @todo   Implement testAddData().
     */
    public function testAddData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::getHttpStatus
     * @todo   Implement testGetHttpStatus().
     */
    public function testGetHttpStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::findLinkByHref
     * @todo   Implement testFindLinkByHref().
     */
    public function testFindLinkByHref()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::findLinkByMethod
     * @todo   Implement testFindLinkByMethod().
     */
    public function testFindLinkByMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::addChildLink
     * @todo   Implement testAddChildLink().
     */
    public function testAddChildLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::addParentLink
     * @todo   Implement testAddParentLink().
     */
    public function testAddParentLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::addSelfLink
     * @todo   Implement testAddSelfLink().
     */
    public function testAddSelfLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::bareResponse
     * @todo   Implement testBareResponse().
     */
    public function testBareResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::getCompleteResponseData
     * @todo   Implement testGetCompleteResponseData().
     */
    public function testGetCompleteResponseData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::doNotIncludeLinks
     * @todo   Implement testDoNotIncludeLinks().
     */
    public function testDoNotIncludeLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
