<?php
namespace HummingJay;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-19 at 22:02:53.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

   
    /**
     * @covers HummingJay\Response::getData
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }


    /**
     * @covers HummingJay\Response::hyperTitle
     * @todo   Implement testHyperTitle().
     */
    public function testHyperTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::hyperDescription
     * @todo   Implement testHyperDescription().
     */
    public function testHyperDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HummingJay\Response::hyperLink
     * @todo   Implement testHyperLink().
     */
    public function testHyperLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }


    /**
     * @covers HummingJay\Response::getHypermedia
     */
    public function testGetHypermedia()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }




    /**
     * @covers HummingJay\Response::addData
     * @todo   Implement testAddData().
     */
    public function testAddData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
